/**
 * @file nut_rom_multifocal.c
 * @brief Implementation - see nut_rom_multifocal.h for the full contract.
 */

#include <assert.h>
#include <stddef.h>
#include <stdint.h>

#define GLOBAL extern
#include "nutcpu.h"

#include "nut_rom_multifocal.h"

/* build/mftest_rom.c (generated by soynut's roms/mod_to_c.py from
 * build/mftest.mod) has no header of its own - declared extern here
 * instead, same pattern nut_rom.c/nut_rom_hpil.c use for their own
 * generated ROM arrays. */
extern const uint16_t rom_mftest_p0[4096];

void nut_rom_wire_multifocal_test_module(void)
{
    /* tabpage[] wants `short *`; the ROM array is `const uint16_t[]` -
     * same const-discard rationale as soynut's own nut_rom.c/nut_boot():
     * typmod[page]==1 (ROM) is never a valid target for wmldl1()'s
     * write path, so nothing ever writes through this pointer. */
    tabpage[8] = (short *)(const void *)rom_mftest_p0;
    typmod[8] = 1;
    assert(tabpage[8] != NULL);
    assert(typmod[8] == 1);
}
