/**
 * @file nut_rom_82180a.c
 * @brief Implementation - see nut_rom_82180a.h for the full contract.
 */

#include <assert.h>
#include <stddef.h>
#include <stdint.h>

#define GLOBAL extern
#include "nutcpu.h"

#include "nut_rom_82180a.h"

/* build/e82180a_rom.c (generated by soynut's roms/mod_to_c.py from the
 * user-sourced 82180A.MOD) has no header of its own - declared extern
 * here instead, same pattern nut_rom.c/nut_rom_multifocal.c use for
 * their own generated ROM arrays. */
extern const uint16_t rom_82180a_p0[4096];

void nut_rom_wire_82180a(void)
{
    /* Page 5 (Port 2), NOT page 4 (Port 1) - see this file's own
     * header comment for the confirmed-broken-for-any-module finding
     * that ruled page 4 out. tabpage[] wants `short *`; the ROM array
     * is `const uint16_t[]` - same const-discard rationale as soynut's
     * own nut_rom.c/nut_boot(): typmod[page]==1 (ROM) is never a valid
     * target for wmldl1()'s write path, so nothing ever writes through
     * this pointer. */
    tabpage[5] = (short *)(const void *)rom_82180a_p0;
    typmod[5] = 1;
    assert(tabpage[5] != NULL);
    assert(typmod[5] == 1);
}
