/**
 * @file nut_rom_cx.c
 * @brief Implementation - see nut_rom_cx.h for the full contract.
 */

#include <assert.h>
#include <stddef.h>
#include <stdint.h>

#define GLOBAL extern
#include "nutcpu.h"

#include "nut_rom_cx.h"

/* build/xnut_rom.c / build/cxfuns_rom.c (generated by soynut's
 * roms/rom_to_c.py) have no header of their own - declared extern here
 * instead, same pattern soynut's own nut_rom.c uses for rom_images.c. */
extern const uint16_t rom_xnut0[4096];
extern const uint16_t rom_xnut1[4096];
extern const uint16_t rom_xnut2[4096];
extern const uint16_t rom_cxfuns0[4096];
extern const uint16_t rom_cxfuns1[4096];

void nut_boot_cx(void)
{
    /* tabpage[] wants `short *`; the ROM arrays are `const uint16_t[]` -
     * same const-discard rationale as soynut's own nut_rom.c/nut_boot():
     * typmod[page]==1 (ROM) is never a valid target for wmldl1()'s
     * write path, so nothing ever writes through these pointers. */
    tabpage[0] = (short *)(const void *)rom_xnut0;
    tabpage[1] = (short *)(const void *)rom_xnut1;
    tabpage[2] = (short *)(const void *)rom_xnut2;
    tabpage[3] = (short *)(const void *)rom_cxfuns0;
    tabpage[4] = (short *)(const void *)rom_cxfuns1;
    typmod[0] = 1;
    typmod[1] = 1;
    typmod[2] = 1;
    typmod[3] = 1;
    typmod[4] = 1;
    assert(tabpage[0] != NULL && tabpage[1] != NULL && tabpage[2] != NULL);
    assert(tabpage[3] != NULL && tabpage[4] != NULL);

    /* Cold-start CPU state - identical to soynut's own nut_rom.c's
     * nut_boot(), just not calling that function directly since it
     * would also wire the plain (non-CX) NUT0-2 pages this function
     * must not use. */
    regPC = 0;
    regST = 0x0800;
    Carry = 1;
    mode_printer = -1;
    assert(regPC == 0 && regST == 0x0800);
    assert(Carry == 1 && mode_printer == (char)-1);
}
