/**
 * @file nut_rom_cx.c
 * @brief Implementation - see nut_rom_cx.h for the full contract.
 */

#include <assert.h>
#include <stddef.h>
#include <stdint.h>

#define GLOBAL extern
#include "nutcpu.h"

#include "nut_rom_cx.h"

/* build/xnut_rom.c / build/cxfuns_rom.c / build/timer_rom.c (generated by
 * soynut's roms/rom_to_c.py) have no header of their own - declared
 * extern here instead, same pattern soynut's own nut_rom.c uses for
 * rom_images.c. */
extern const uint16_t rom_xnut0[4096];
extern const uint16_t rom_xnut1[4096];
extern const uint16_t rom_xnut2[4096];
extern const uint16_t rom_cxfuns0[4096];
extern const uint16_t rom_cxfuns1[4096];
extern const uint16_t rom_timer[4096];

void nut_boot_cx(void)
{
    /* CORRECTED WIRING (was: CXFUNS1 at flat page 4 - WRONG). Real
     * HP-41CX page map (confirmed via px41cx-utility's own config,
     * cross-checked against emu41gcc's own enrom() CXTIME bank-switch
     * case at nutcpu.c ~line 318): pages 0-3 are flat ROM (XNUT0-2,
     * CXFUN0); page 5 is BANK-SWITCHED between TIMER (bank 0) and
     * CXFUN1 (bank 1) - typmod[5]=2 selects emu41gcc's existing
     * "CXTIME" case, which real HP-41 OS code already knows how to
     * ENROM(5,n) between. Page 4 is not used by this configuration at
     * all. This was the root cause of RESZFL/SEEKPT/SAVEP/EMROOM
     * crashing: code in CXFUN0 (page 3) that needs to reach CXFUN1
     * jumped into page 5, which was never wired - CRFLD/SAVEX/GETX
     * happened to stay entirely within page 3 and so never hit this.
     *
     * tabpage[] wants `short *`; the ROM arrays are `const uint16_t[]` -
     * same const-discard rationale as soynut's own nut_rom.c/nut_boot():
     * typmod[page]==1 (ROM) is never a valid target for wmldl1()'s
     * write path, so nothing ever writes through these pointers. */
    tabpage[0] = (short *)(const void *)rom_xnut0;
    tabpage[1] = (short *)(const void *)rom_xnut1;
    tabpage[2] = (short *)(const void *)rom_xnut2;
    tabpage[3] = (short *)(const void *)rom_cxfuns0;
    typmod[0] = 1;
    typmod[1] = 1;
    typmod[2] = 1;
    typmod[3] = 1;

    tabbank[5][0] = (short *)(const void *)rom_cxfuns1;
    tabbank[5][1] = (short *)(const void *)rom_timer;
    typmod[5] = 2; /* CXTIME - bank-switched, see enrom() */
    tabpage[5] = tabbank[5][0]; /* cold-start default bank, mirrors enrom(5,0) "reset to bloc A" */

    assert(tabpage[0] != NULL && tabpage[1] != NULL && tabpage[2] != NULL);
    assert(tabpage[3] != NULL && tabpage[5] != NULL);

    /* Cold-start CPU state - identical to soynut's own nut_rom.c's
     * nut_boot(), just not calling that function directly since it
     * would also wire the plain (non-CX) NUT0-2 pages this function
     * must not use. */
    regPC = 0;
    regST = 0x0800;
    Carry = 1;
    mode_printer = -1;
    assert(regPC == 0 && regST == 0x0800);
    assert(Carry == 1 && mode_printer == (char)-1);
}
